# Specify intial version
version: '3.7'

# First service is postgres database
services:
  db:
    image: postgres:14.1
    restart: always
    container_name: postgres
    ports: 
      - '33867:3386'
    environment:
      - POSTGRES_DB=testpayroll
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'

  # Second service is payroll container (flask backend)
  payroll:
    container_name: payroll
    # Runs Dockerfile build in the current directory
    build:
      context: ./backend
    # Allows program to print to terminal
    environment:
      - PYTHONUNBUFFERED=1
    # Name of the payroll image with version
    image: payroll:latest
    # Exposes host port to container port for communication
    ports:
      - 5001:5000
    volumes: 
      - ./backend:/app
    depends_on:
      - db

  # Third service is the react front end (work in progress)


# Used to create a persistant db even after container killed (maybe?)
volumes:
  postgres_data: